// <auto-generated />
using FADY.Services.Employee.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FADY.Services.Employee.Infrastructure.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FADY.Services.Employee.Dmoain.AggregatesModel.EmployeeAggregate.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EmpId");

                    b.Property<string>("ImagePath");

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<int>("Submitted");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("FADY.Services.Employee.Dmoain.AggregatesModel.EmployeeAggregate.Employe", b =>
                {
                    b.OwnsOne("FADY.Services.Employee.Dmoain.AggregatesModel.EmployeeAggregate.Address", "Address", b1 =>
                        {
                            b1.Property<int>("EmployeId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("City")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Street")
                                .HasColumnName("Address_Street");

                            b1.HasKey("EmployeId");

                            b1.ToTable("Employees");

                            b1.HasOne("FADY.Services.Employee.Dmoain.AggregatesModel.EmployeeAggregate.Employe")
                                .WithOne("Address")
                                .HasForeignKey("FADY.Services.Employee.Dmoain.AggregatesModel.EmployeeAggregate.Address", "EmployeId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
